### ISSUE TITLE
Invalid hotkey at line 341

### ISSUE THREAD

**Issue by priyadarshan** [usi3/emacs.ahk#3]
Hello,

Thank you for sharing `emacs.ahk`, I have been looking for something like this for ages!

When I launch it using Windows 10 (build 17763) and AutoHotKey v. 1.1.30.03 I get this error message:
 
```
>"C:\Program Files\AutoHotkey\AutoHotkey.exe" /ErrorStdOut "C:\home\bin\emacs.ahk"    
C:\home\bin\emacs.ahk (341) : ==> Invalid hotkey.
     Specifically: ^vk20sc039::
>Exit code: 2    Time: 0.1319
```

Thank you again.

**Comment by usi3** [comment]
Hello,

Many thanks for pointing out this issue. I fixed it by replacing "vk20sc039" with "vk20".

**Comment by priyadarshan** [comment]
Wonderful, thank you. I can confirm it works on my side too.

Thank you again for the excellent `emacs.ahk`, it made Windows 10 a nice and livable place for me.
